In [950]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import math
import random


In [951]:


def gen_momentum_vectors(N):
    #generate random 2d, unit vectors ---> (x, z)
    x_vals = np.random.uniform(-1, 1, size = N)
    z_vals = np.random.uniform(-1, 1, size = N)
    
    J_plus = np.asarray([np.asarray([x, z]).reshape(2,1) for x, z in zip(x_vals, z_vals)])
    J_minus = np.asarray([-1*Jp for Jp in J_plus])
    
    return [J_plus, J_minus]


vecs = gen_momentum_vectors(10)


vecs[1]    


array([[[-0.11248274],
        [-0.95355791]],

       [[-0.0701281 ],
        [-0.861393  ]],

       [[-0.06184476],
        [-0.35027806]],

       [[ 0.98974363],
        [ 0.61620595]],

       [[ 0.38072732],
        [-0.72663546]],

       [[-0.49913809],
        [ 0.33820718]],

       [[-0.53400111],
        [-0.90245123]],

       [[-0.56717039],
        [-0.0474527 ]],

       [[-0.3536352 ],
        [-0.35940999]],

       [[-0.09862035],
        [ 0.14778847]]])

In [952]:
vecs[0]

array([[[ 0.11248274],
        [ 0.95355791]],

       [[ 0.0701281 ],
        [ 0.861393  ]],

       [[ 0.06184476],
        [ 0.35027806]],

       [[-0.98974363],
        [-0.61620595]],

       [[-0.38072732],
        [ 0.72663546]],

       [[ 0.49913809],
        [-0.33820718]],

       [[ 0.53400111],
        [ 0.90245123]],

       [[ 0.56717039],
        [ 0.0474527 ]],

       [[ 0.3536352 ],
        [ 0.35940999]],

       [[ 0.09862035],
        [-0.14778847]]])

In [953]:
def gen_measurement_vector(theta):
    #generate a measurement vector --> (x,z)
    #functions assume radians
    components = np.array(([np.sin(theta),np.cos(theta)]))
    magnitude = math.sqrt(sum(pow(element, 2) for element in components))
    unit_vector = components/magnitude
    return unit_vector



gen_measurement_vector(np.pi/4)

array([0.70710678, 0.70710678])

In [954]:
def experiment(theta, number_of_momentum_vectors):
    
    #creates 4 experiement vectors from input theta
    alpha_1 = gen_measurement_vector(0*theta)
    alpha_2 = gen_measurement_vector(theta)
    beta_1 = gen_measurement_vector(theta)
    beta_2 = gen_measurement_vector(2*theta)
    
    #used to calcuate correlators 
    alpha_1_beta_1 = [] 
    alpha_2_beta_1 = [] 
    alpha_1_beta_2 = [] 
    alpha_2_beta_2 = []
    
    #creates N momentum vectors
    momentum_vectors = gen_momentum_vectors(number_of_momentum_vectors)
   
    #does experiment
    for up_momentum_vectors in momentum_vectors[0]:
        #randomly chooses an alpha and a beta
        #print(np.random.uniform(0, 1, size = 1)[0])
        counter_alpha = 0 
        counter_beta = 0
        if random.randint(1, 2)  == 1:
            measurement_1 = alpha_1
            counter_alpha += 1
        else: 
            measurement_1 = alpha_2
            counter_alpha += 2
            
        if random.randint(1, 2) == 1:
            measurement_2 = beta_1
            counter_beta += 1
        else: 
            measurement_2 = beta_2
            counter_beta += 2
        #normalize momentum vectors
        components = np.array(up_momentum_vectors)
        magnitude = math.sqrt(sum(pow(element, 2) for element in components))
        unit_vector = components/magnitude
        
       
        
        #measurements
        a_alpha_i = np.sign(np.dot(measurement_1,unit_vector))
        b_beta_i = -np.sign(np.dot(measurement_2,unit_vector))
        measurement = a_alpha_i[0]*b_beta_i[0]
        
        
        #sorts measruements into 4 correlators to later calculate CHSH correlator
        
        #problem here alpha_2_beta_1 array not populating
        if counter_alpha == 1 and counter_beta == 1:
            alpha_1_beta_1.append(measurement)
        if counter_alpha == 1 and counter_beta == 2: 
            alpha_1_beta_2.append(measurement)
        if counter_alpha == 2 and counter_beta == 1:
            alpha_2_beta_1.append(measurement)
        if counter_alpha == 2 and counter_beta == 2:
            alpha_2_beta_2.append(measurement)
        
    #print(alpha_1_beta_1,alpha_1_beta_2,alpha_2_beta_1,alpha_2_beta_2)
        
    
    correlator_11 = np.sum(alpha_1_beta_1)/len(alpha_1_beta_1)
    correlator_12 = np.sum(alpha_1_beta_2)/len(alpha_1_beta_2)
    correlator_21 = np.sum(alpha_2_beta_1)/len(alpha_2_beta_1) 
    correlator_22 = np.sum(alpha_2_beta_2)/len(alpha_2_beta_2)
    
    S = correlator_11 + correlator_12 + correlator_21 - correlator_22    
        
    
    return S

for angle in np.linspace(0,2*np.pi,32):
        #print("Correlator: ", experiment(angle,2000), "Angle(in radians): ", angle)
        print( experiment(angle,2000), angle)

Correlator:  -2.0 Angle:  0.0
Correlator:  -1.7776696727343524 Angle:  0.2026833970057931
Correlator:  -1.5727671043985534 Angle:  0.4053667940115862
Correlator:  -1.3191586511976632 Angle:  0.6080501910173793
Correlator:  -0.8875573252527036 Angle:  0.8107335880231724
Correlator:  -0.6088225196900499 Angle:  1.0134169850289656
Correlator:  -0.4824448924397944 Angle:  1.2161003820347587
Correlator:  -0.21575652280349197 Angle:  1.4187837790405518
Correlator:  -0.06305901173216183 Angle:  1.6214671760463448
Correlator:  -0.26848010576755676 Angle:  1.824150573052138
Correlator:  -0.7610983279644117 Angle:  2.026833970057931
Correlator:  -0.8496422035167 Angle:  2.2295173670637243
Correlator:  -1.0368412709450385 Angle:  2.4322007640695174
Correlator:  -1.1099874026282557 Angle:  2.6348841610753104
Correlator:  -1.636917746200061 Angle:  2.8375675580811035
Correlator:  -1.814538753913713 Angle:  3.0402509550868966
Correlator:  -1.8579769082532755 Angle:  3.2429343520926897
Correlator:  -