In [871]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import math
import random


In [872]:


def gen_momentum_vectors(N):
    #generate random 2d, unit vectors ---> (x, z)
    x_vals = np.random.uniform(-1, 1, size = N)
    z_vals = np.random.uniform(-1, 1, size = N)
    
    J_plus = np.asarray([np.asarray([x, z]).reshape(2,1) for x, z in zip(x_vals, z_vals)])
    J_minus = np.asarray([-1*Jp for Jp in J_plus])
    
    return [J_plus, J_minus]


vecs = gen_momentum_vectors(10)


vecs[1]    


array([[[ 0.97772371],
        [ 0.73699015]],

       [[ 0.46377807],
        [-0.15507994]],

       [[-0.13017452],
        [ 0.83220455]],

       [[-0.77820009],
        [ 0.28664686]],

       [[-0.60579801],
        [ 0.55207488]],

       [[-0.94018466],
        [-0.75514038]],

       [[-0.59654498],
        [-0.47361411]],

       [[ 0.44141348],
        [ 0.36577543]],

       [[-0.07946467],
        [ 0.2704553 ]],

       [[-0.14594304],
        [-0.84443443]]])

In [873]:
vecs[0]

array([[[-0.97772371],
        [-0.73699015]],

       [[-0.46377807],
        [ 0.15507994]],

       [[ 0.13017452],
        [-0.83220455]],

       [[ 0.77820009],
        [-0.28664686]],

       [[ 0.60579801],
        [-0.55207488]],

       [[ 0.94018466],
        [ 0.75514038]],

       [[ 0.59654498],
        [ 0.47361411]],

       [[-0.44141348],
        [-0.36577543]],

       [[ 0.07946467],
        [-0.2704553 ]],

       [[ 0.14594304],
        [ 0.84443443]]])

In [874]:
def gen_measurement_vector(theta):
    #generate a measurement vector --> (x,z)
    #functions assume radians
    components = np.array(([np.sin(theta),np.cos(theta)]))
    magnitude = math.sqrt(sum(pow(element, 2) for element in components))
    unit_vector = components/magnitude
    return unit_vector



gen_measurement_vector(np.pi/4)

array([0.70710678, 0.70710678])

In [875]:
def experiment(theta, number_of_momentum_vectors):
    
    #creates 4 experiement vectors from input theta
    alpha_1 = gen_measurement_vector(0*theta)
    alpha_2 = gen_measurement_vector(theta)
    beta_1 = gen_measurement_vector(theta)
    beta_2 = gen_measurement_vector(2*theta)
    
    #used to calcuate correlators 
    alpha_1_beta_1 = [] 
    alpha_2_beta_1 = [] 
    alpha_1_beta_2 = [] 
    alpha_2_beta_2 = []
    
    #creates N momentum vectors
    momentum_vectors = gen_momentum_vectors(number_of_momentum_vectors)
   
    #does experiment
    for up_momentum_vectors in momentum_vectors[0]:
        #randomly chooses an alpha and a beta
        #print(np.random.uniform(0, 1, size = 1)[0])
        counter_alpha = 0 
        counter_beta = 0
        if random.randint(1, 2)  == 1:
            measurement_1 = alpha_1
            counter_alpha += 1
        else: 
            measurement_1 = alpha_2
            counter_alpha += 2
            
        if random.randint(1, 2) == 1:
            measurement_2 = beta_1
            counter_beta += 1
        else: 
            measurement_2 = beta_2
            counter_beta += 2
        #normalize momentum vectors
        components = np.array(up_momentum_vectors)
        magnitude = math.sqrt(sum(pow(element, 2) for element in components))
        unit_vector = components/magnitude
        
       
        
        #measurements
        a_alpha_i = np.sign(np.dot(measurement_1,unit_vector))
        b_beta_i = -np.sign(np.dot(measurement_2,unit_vector))
        measurement = a_alpha_i[0]*b_beta_i[0]
        
        
        #sorts measruements into 4 correlators to later calculate CHSH correlator
        
        #problem here alpha_2_beta_1 array not populating
        if counter_alpha == 1 & counter_beta == 1:
            alpha_1_beta_1.append(measurement)
        elif counter_alpha == 1 & counter_beta == 2: 
            alpha_1_beta_2.append(measurement)
        elif counter_alpha == 2 & counter_beta == 1:
            alpha_2_beta_1.append(measurement)
        elif counter_alpha == 2 & counter_beta == 2:
            alpha_2_beta_2.append(measurement)
        
    
    correlator_11 = np.sum(alpha_1_beta_1)/len(alpha_1_beta_1)
    correlator_12 = np.sum(alpha_1_beta_2)/len(alpha_1_beta_2)
    correlator_21 = np.sum(alpha_2_beta_1)/len(alpha_2_beta_1) 
    correlator_22 = np.sum(alpha_2_beta_2)/len(alpha_2_beta_2)
    
    S = correlator_11 + correlator_12 + correlator_21 - correlator_22    
        
    
    return S
    
experiment(np.pi/4,2000)

C:\Users\jacob\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:64: RuntimeWarning: invalid value encountered in double_scalars
C:\Users\jacob\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel_launcher.py:65: RuntimeWarning: invalid value encountered in double_scalars


nan